name: CI Build for Docker Action
on: 
  push: 
    branches: 
      - main 
    paths:
      - hello-world-docker-action/**
  workflow_dispatch:

jobs:
  test-action: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout 
        uses: actions/checkout@v3.3.0
      
      - name: Runnit 
        id: hello-action
        uses: ./hello-world-docker-action
        with: 
          who-to-greet: "@json" 
      
      - name: Whenisit
        run: echo "time was ${{ steps.hello-action.outputs.time }} when someone said hellow" 
